import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/providers/theme-provider";
import type { Metadata } from "next";
import { Exo_2, Open_Sans } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";

import ContextProvider from "@/providers/context-provider";

const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open-sans',
  weight: ['300', '400', '500', '600', '700', '800'],
});
const exo2 = Exo_2({
  subsets: ['latin'],
  variable: '--font-exo2',
  weight: ['400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${openSans.className} ${exo2.variable} antialiased`}
      >
        <NextTopLoader initialPosition={0.2} color="#888" />
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ContextProvider>
            {children}
          </ContextProvider>
          <Toaster richColors />
        </ThemeProvider>
      </body>
    </html>
  );
}
